stages:
  - install
  - lint
  - build
  - deploy

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
    - packages/**/dist/

install:
  stage: install
  only:
    refs:
      - master
      - merge_requests
      - /^release-v\d(\d|\d\.\d)*$/i
  tags:
    - linux-runner
  script:
    - yarn install

build:
  stage: build
  only:
    refs:
      - master
      - merge_requests
      - /^release-v\d(\d|\d\.\d)*$/i
  tags:
    - linux-runner
  script:
    - yarn workspace badanmu build

lint:
  stage: lint
  only:
    refs:
      - master
      - merge_requests
      - /^release-v\d(\d|\d\.\d)*$/i
  tags:
    - linux-runner
  script:
    - yarn workspace badanmu lint --quiet

deploy:
  stage: deploy
  when: manual
  only:
    refs:
      - /^release-v\d(\d|\d\.\d)*$/i
      - web
      - tags
    changes:
      - packages/badanmu/src
  tags:
    - linux-runner
  script:
    # 同步文件
    - rsync --delete -av --exclude="node_modules" --exclude="logs" --exclude="*.log" --exclude=".DS_Store" ./packages/badanmu/ bin@124.70.83.120:/cygdrive/c/webserver/badanmu
    # 依次部署所有服务
    - ssh bin@124.70.83.120 'cd /cygdrive/c/webserver/badanmu/ && sh ./deploy.sh'
