stages:
  - install
  - build

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
    - dist

install:
  stage: install
  tags:
    - hub
  script:
    - yarn install

build:
  stage: build
  tags:
    - a
  script:
    - yarn workspace badanmu build
