stages:
  - install
  - build
  - deploy

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
    - packages/**/dist

install:
  stage: install
  tags:
    - hub
  script:
    - yarn install

build:
  stage: build
  tags:
    - hub
  script:
    - yarn workspace badanmu build

deploy:
  stage: deploy
  tags:
    - hub
  script:
    - mv -r ./ ~/Developer/gitlab-runner/
