stages:
  - install
  - lint
  - build
  - deploy

install:
  stage: install
  only:
    refs:
      - master
      - merge_requests
  tags:
    - hub
  script:
    - yarn install
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/

build:
  stage: build
  only:
    refs:
      - master
      - merge_requests
  tags:
    - hub
  script:
    - yarn workspace badanmu build

lint:
  stage: lint
  only:
    refs:
      - master
      - merge_requests
  tags:
    - hub
  script:
    - yarn workspace badanmu lint --quiet

deploy:
  stage: deploy
  only:
    refs:
      - master
  tags:
    - hub
  script:
    - echo "deploy"
    # # 同步文件
    # - rsync --delete -av --exclude="node_modules" --exclude="logs" --exclude="*.log" --exclude=".DS_Store" ./packages/badanmu/ bin@124.70.83.120:/cygdrive/c/webserver/badanmu-8000
    # # 依次部署所有服务
    # - ssh bin@124.70.83.120 'cd /cygdrive/c/webserver/badanmu/ && sh ./deploy.sh'
