stages:
  - install
  - build

install:
  stage: install
  tags:
    - a
  only:
    refs:
      - merge_requests
  script:
    - yarn install

build:
  stage: build
  tags:
    - a
  script:
    - yarn workspace badanmu build
